version: '3'

services:
  client:
    build: ./client
    ports:
      - "3003:80"
    depends_on:
      - server
    environment:
      - SERVER=server:5001


  server:
    build: ./server
    ports: 
      - "5001:5001"
    depends_on:
      - mongo


  mongo:
    image: mongo
    ports:
     - "27107:27107"