apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: "0 3 * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-backup-container
            image: mongo:latest
            command: ["/bin/sh", "-c"]
            args:
            - mongodump --host=mongo --port=27017 --out=/backup  
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          volumes:
          - name: backup-volume
            emptyDir: {}
          restartPolicy: OnFailure
