apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: server-hpa
spec:
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization 
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: server