apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mongodb
spec:
 serviceName: "mongodb-service"
 replicas: 3
 selector:
   matchLabels:
     app: mongodb
 template:
   metadata:
     labels:
       app: mongodb
   spec:
     containers:
     - name: mongodb
       image: mongo:latest
       ports:
       - containerPort: 27017
       volumeMounts:
       - name: mongo-persistent-storage
         mountPath: /data/db
 volumeClaimTemplates:
 - metadata:
     name: mongo-persistent-storage
   spec:
     accessModes: [ "ReadWriteOnce" ]
     storageClassName: ebs-gp3
     resources:
       requests:
         storage: 1Gi